export const EXPENSE_REQUEST = 'EXPENSE_REQUEST';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const SAVE_EDITED_EXPENSE = 'SAVE_EDITED_EXPENSE';
export const SET_ASK_TO_FALSE = 'SET_ASK_TO_FALSE';
export const SET_DELETE_TO_FALSE = 'SET_DELETE_TO_FALSE';
